defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "validation/val_loss" # name of the logged metric which determines when model is improving
  mode: "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "validation/ema_loss" # name of the logged metric which determines when model is improving
  mode: "min" # "max" means higher metric value is better, can be also "min"
  patience: 25 # how many validation epochs of not improving until training stops
  min_delta: 1e-6 # minimum change in the monitored metric needed to qualify as an improvement

model_summary:
  max_depth: 5

ema_loss:
  _target_: goflow.gotennet.models.components.callbacks.EMALossCallback
  alpha: 0.9
  soft_beta: 2.5

test_and_save_after_training:
  _target_: goflow.gotennet.models.components.callbacks.TestAndSaveResultsAfterTrainingCallback
  save_path: ${hydra:runtime.output_dir}
  runs_stats_path: ${paths.log_dir}/${task_name}
  #mr_stats_path: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}

#learning_rate_monitor:
#  _target_: lightning.pytorch.callbacks.LearningRateMonitor