# specify here default configuration
# order of defaults determines the order in which configs override each other
# self at the end: Primary config values take precedence
# self at the beginning: Defaults list values take precedence
defaults:
  - data: rdb7
  - model: flow
  - callbacks: default
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - _self_
  
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
project: "flow-matching-gotennet" # wandb project name
task_name: "eval"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True
custom_model_weight_path: logs/eval/runs/2025-04-08_14-23-27/checkpoints/epoch_347.ckpt #flow1.ckpt

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 1
model:
  seed: ${seed}
  
data:
  split_file: random_split.pkl


#name: "goflow_data"
#task: "RDB7"
#label: -1
#label_str: -1